# Generated by Django 4.2.7 on 2024-01-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realOwner", "0003_alter_item_category_alter_item_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="location",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
