# Generated by Django 4.2.7 on 2024-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("realOwner", "0011_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
