# Generated by Django 4.2.7 on 2024-02-23 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("realOwner", "0014_remove_item_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="previous_owner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="store_date_of_purchase",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="item",
            name="store_of_purchase",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="warranty",
            field=models.TextField(blank=True, null=True),
        ),
    ]
