# Generated by Django 4.2.7 on 2024-02-23 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("realOwner", "0015_item_previous_owner_item_store_date_of_purchase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="realOwner.category",
            ),
        ),
    ]
