# Generated by Django 4.2.7 on 2024-03-02 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("realOwner", "0018_brand_description_alter_brand_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Phone",
            new_name="phone_category",
        ),
    ]
