# Generated by Django 4.2.7 on 2024-03-02 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("realOwner", "0019_rename_phone_phone_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="phone_category",
            new_name="PhoneCategory",
        ),
    ]
