# Generated by Django 4.2.7 on 2024-03-04 05:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("realOwner", "0021_item_description_alter_phonecategory_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonecategory",
            name="color",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="phonecategory",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="phonecategory",
            name="previous_owner",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="phonecategory",
            name="serial_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="phonecategory",
            name="store_date_of_purchase",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="phonecategory",
            name="store_of_purchase",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="phonecategory",
            name="warranty",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="phonecategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phones",
                to="realOwner.category",
            ),
        ),
    ]
